In [50]:

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [51]:
# read the dataset

data = pd.read_csv(r"C:\Users\NEHA1\Documents\Summer Analystics Assignments\Hackathon_1\dataset and all\training_set_features.csv")
data.head(10)

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb
5,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,atmpeygn,"MSA, Principle City",2.0,3.0,saaquncn,vlluhbov
6,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",0.0,0.0,xicduogh,xtkaffoo
7,7,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,bhuqouqj,Non-MSA,2.0,0.0,pxcmvdjn,xqwwgdyp
8,8,0.0,2.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,"> $75,000",Married,Own,Employed,bhuqouqj,"MSA, Not Principle City",1.0,0.0,xicduogh,ccgxvspp
9,9,2.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,qufhixun,"MSA, Not Principle City",0.0,0.0,NaN,NaN

In [52]:
data.columns

Index(['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa',
       'household_adults', 'household_children', 'employment_industry',
       'employment_occupation'],
      dtype='object')

In [53]:
# handling missing values
data.isnull().sum()

respondent_id                      0
xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
hhs_geo_region                     0
census_msa                         0
household_adults                 249
household_children               249
employment_industry            13330
employment_occupation          13470
dtype: int64

In [54]:
data.shape

(26707, 36)

In [90]:
# handle missing values
imputer = SimpleImputer(strategy='most_frequent')
data_imputed= imputer.fit_transform(data)
data_imputed = pd.DataFrame(data_imputed, columns=data.columns)
data_imputed

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,fcxhlnwr,xtkaffoo
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,fcxhlnwr,xtkaffoo
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,fcxhlnwr,xtkaffoo
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,"MSA, Not Principle City",0.0,0.0,fcxhlnwr,xtkaffoo
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,fcxhlnwr,xtkaffoo

In [92]:
data.dtypes

respondent_id                    int64
xyz_concern                    float64
xyz_knowledge                  float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_xyz                float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_xyz_vacc_effective     float64
opinion_xyz_risk               float64
opinion_xyz_sick_from_vacc     float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                       object
education                       object
race                            object
sex                             object
income_poverty                  object
marital_status                  object
rent_or_own                     object
employment_status               object
hhs_geo_region                  object
census_msa                      object
household_adults               float64
household_children             float64
employment_industry             object
employment_occupation           object
dtype: object

In [57]:
# encoding the categorical features having object as dtypes

categorical_features = data.select_dtypes(include=['object']).columns
catego

In [103]:
categorical_features

Index(['age_group', 'education', 'race', 'sex', 'income_poverty',
       'marital_status', 'rent_or_own', 'employment_status', 'hhs_geo_region',
       'census_msa', 'employment_industry', 'employment_occupation'],
      dtype='object')

In [84]:
data_imputed.isnull().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_region                 0
census_msa                     0
household_adults               0
household_children             0
employment_industry            0
employment_occupation          0
dtype: int64

In [85]:
data_imputed['income_poverty'].value_counts()

income_poverty
<= $75,000, Above Poverty    17200
> $75,000                     6810
Below Poverty                 2697
Name: count, dtype: int64

In [86]:
data_imputed['age_group'].value_counts()

age_group
65+ Years        6843
55 - 64 Years    5563
45 - 54 Years    5238
18 - 34 Years    5215
35 - 44 Years    3848
Name: count, dtype: int64

In [87]:
data_imputed['education'].value_counts()

education
College Graduate    11504
Some College         7043
12 Years             5797
< 12 Years           2363
Name: count, dtype: int64

In [88]:
data_imputed['employment_occupation'].value_counts()

employment_occupation
xtkaffoo    15248
mxkfnird     1509
emcorrxb     1270
cmhcxjea     1247
xgwztkwe     1082
hfxkjkmi      766
qxajmpny      548
xqwwgdyp      485
kldqjyjy      469
uqqtjvyb      452
tfqavkke      388
ukymxvdu      372
vlluhbov      354
oijqvulv      344
ccgxvspp      341
bxpfxfdn      331
haliazsg      296
rcertsgn      276
xzmlyyjv      248
dlvbwzss      227
hodpvpew      208
dcjcmpih      148
pvmttkik       98
Name: count, dtype: int64

In [83]:
# we will perform the ordinal encoding for age_group, education, income_poverty features

age_group_map ={'18 - 34 Years':1,'35 - 44 Years':2, '45 - 54 Years':3, '55 - 64 Years':4, '65+ Years':5 }
education_map ={'< 12 Years':1,'12 Years':2, 'Some College':3, 'College Graduate':4 }
income_poverty_map ={'Below Poverty':1,'> $75,000':2, '<= $75,000, Above Poverty':3 }

In [94]:
data_imputed['age_group_map']= data_imputed['age_group'].map(age_group_map)

In [96]:
data_imputed['education_map']= data_imputed['education'].map(education_map)
data_imputed['income_poverty_map']= data_imputed['income_poverty'].map(income_poverty_map)
data_imputed

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,age_group_map,education_map,income_poverty_map
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,fcxhlnwr,xtkaffoo,4,1,1
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,2,2,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,1,4,3
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,fcxhlnwr,xtkaffoo,5,2,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,fcxhlnwr,xtkaffoo,5,3,3
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea,1,4,3
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,Employed,lzgpxyit,"MSA, Not Principle City",0.0,0.0,fcxhlnwr,xtkaffoo,4,3,3
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg,1,3,3
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,fcxhlnwr,xtkaffoo,5,3,3

In [100]:
# now we will perform frequency or count encoding for the remaining categorical features

categorical_remaining_features = [ 'race', 'sex', 'marital_status', 'rent_or_own', 'employment_status', 'hhs_geo_region',
       'census_msa', 'employment_industry', 'employment_occupation']

In [98]:
def map_value_counts(df, categorical_features):
    
    for feature in categorical_features:
        count_map = df[feature].value_counts().to_dict()
        df[f'{feature}_map'] = df[feature].map(count_map)
        
    return df

In [101]:
map_value_counts(data_imputed,categorical_remaining_features )

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty_map,race_map,sex_map,marital_status_map,rent_or_own_map,employment_status_map,hhs_geo_region_map,census_msa_map,employment_industry_map,employment_occupation_map
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,21222,15858,11744,20778,10231,2859,7198,15798,15248
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1,21222,10849,11744,5929,15023,2846,11645,1037,1082
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3,21222,10849,11744,20778,15023,3102,11645,523,15248
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1,21222,15858,11744,5929,10231,2078,7864,15798,15248
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,3,21222,15858,14963,20778,15023,3102,11645,1804,1270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,3,21222,15858,11744,20778,10231,3102,7198,15798,15248
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,3,21222,10849,11744,5929,15023,4297,7864,15798,1247
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,3,21222,15858,11744,20778,15023,4297,11645,15798,15248
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,3,1755,15858,14963,5929,15023,2078,7198,15798,296
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3,21222,10849,14963,20778,10231,2243,7864,15798,15248

In [108]:
data_imputed.drop(categorical_features, axis=1, inplace=True)

In [109]:
data_imputed

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty_map,race_map,sex_map,marital_status_map,rent_or_own_map,employment_status_map,hhs_geo_region_map,census_msa_map,employment_industry_map,employment_occupation_map
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,21222,15858,11744,20778,10231,2859,7198,15798,15248
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1,21222,10849,11744,5929,15023,2846,11645,1037,1082
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3,21222,10849,11744,20778,15023,3102,11645,523,15248
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1,21222,15858,11744,5929,10231,2078,7864,15798,15248
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,3,21222,15858,14963,20778,15023,3102,11645,1804,1270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,3,21222,15858,11744,20778,10231,3102,7198,15798,15248
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,3,21222,10849,11744,5929,15023,4297,7864,15798,1247
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,3,21222,15858,11744,20778,15023,4297,11645,15798,15248
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,3,1755,15858,14963,5929,15023,2078,7198,15798,296
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3,21222,10849,14963,20778,10231,2243,7864,15798,15248

In [110]:
data_imputed.dtypes

respondent_id                  object
xyz_concern                    object
xyz_knowledge                  object
behavioral_antiviral_meds      object
behavioral_avoidance           object
behavioral_face_mask           object
behavioral_wash_hands          object
behavioral_large_gatherings    object
behavioral_outside_home        object
behavioral_touch_face          object
doctor_recc_xyz                object
doctor_recc_seasonal           object
chronic_med_condition          object
child_under_6_months           object
health_worker                  object
health_insurance               object
opinion_xyz_vacc_effective     object
opinion_xyz_risk               object
opinion_xyz_sick_from_vacc     object
opinion_seas_vacc_effective    object
opinion_seas_risk              object
opinion_seas_sick_from_vacc    object
household_adults               object
household_children             object
age_group_map                   int64
education_map                   int64
income_poverty_map              int64
race_map                        int64
sex_map                         int64
marital_status_map              int64
rent_or_own_map                 int64
employment_status_map           int64
hhs_geo_region_map              int64
census_msa_map                  int64
employment_industry_map         int64
employment_occupation_map       int64
dtype: object

In [111]:
# Normalizing with the help of StandardScaler

from sklearn.preprocessing import StandardScaler

In [127]:
scaler = StandardScaler()
data_imputed_scaled = scaler.fit_transform(data_imputed)

In [128]:
data_imputed_scaled

array([[-0.68184881, -2.04427905, -0.22629268, ..., -1.0424962 ,
         0.83018074,  0.86611227],
       [ 1.51837305,  1.19702709, -0.22629268, ...,  1.12879785,
        -1.18436484, -1.1143557 ],
       [-0.68184881, -0.42362598, -0.22629268, ...,  1.12879785,
        -1.25451431,  0.86611227],
       ...,
       [ 0.41826212,  1.19702709, -0.22629268, ...,  1.12879785,
         0.83018074,  0.86611227],
       [-0.68184881, -0.42362598, -0.22629268, ..., -1.0424962 ,
         0.83018074, -1.22424189],
       [-1.78195974, -2.04427905, -0.22629268, ..., -0.71731476,
         0.83018074,  0.86611227]])

In [114]:
# Spliting the data into training and testing sets

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

In [115]:
df=pd.read_csv(r"C:\Users\NEHA1\Documents\Summer Analystics Assignments\Hackathon_1\dataset and all\training_set_labels.csv")
df

       respondent_id  xyz_vaccine  seasonal_vaccine
0                  0            0                 0
1                  1            0                 1
2                  2            0                 0
3                  3            0                 1
4                  4            0                 0
...              ...          ...               ...
26702          26702            0                 0
26703          26703            0                 0
26704          26704            0                 1
26705          26705            0                 0
26706          26706            0                 0

[26707 rows x 3 columns]

In [120]:

data_imputed =pd.merge(data_imputed, df, on='respondent_id', how='left')
# this is showing error because we have already run this cell many times and duplicate formed, so we have to drop the duplicated columns

MergeError: Passing 'suffixes' which cause duplicate columns {'seasonal_vaccine_x', 'xyz_vaccine_x'} is not allowed.

In [122]:
data_xyz=data_imputed['xyz_vaccine']
data_seasonal = data_imputed['seasonal_vaccine']

In [125]:
# we will drop the non usefull columns
data_imputed.drop(['xyz_vaccine_x','seasonal_vaccine_x','xyz_vaccine_y','seasonal_vaccine_y','xyz_vaccine','seasonal_vaccine', 'respondent_id' ], axis=1, inplace=True)

In [126]:
data_imputed

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,income_poverty_map,race_map,sex_map,marital_status_map,rent_or_own_map,employment_status_map,hhs_geo_region_map,census_msa_map,employment_industry_map,employment_occupation_map
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1,21222,15858,11744,20778,10231,2859,7198,15798,15248
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1,21222,10849,11744,5929,15023,2846,11645,1037,1082
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,21222,10849,11744,20778,15023,3102,11645,523,15248
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1,21222,15858,11744,5929,10231,2078,7864,15798,15248
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,3,21222,15858,14963,20778,15023,3102,11645,1804,1270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,3,21222,15858,11744,20778,10231,3102,7198,15798,15248
26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,3,21222,10849,11744,5929,15023,4297,7864,15798,1247
26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,3,21222,15858,11744,20778,15023,4297,11645,15798,15248
26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3,1755,15858,14963,5929,15023,2078,7198,15798,296
26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,21222,10849,14963,20778,10231,2243,7864,15798,15248

In [129]:
#Splitting the data into training and testing sets
data_train, data_test, data_xyz_train, data_xyz_test, data_seasonal_train, data_seasonal_test = train_test_split(data_imputed_scaled, data_xyz, data_seasonal, test_size=0.2, random_state=42)

# Initialize the models
model_xyz = RandomForestClassifier(random_state=42)
model_seasonal = RandomForestClassifier(random_state=42)

In [130]:
# Training the models
model_xyz.fit(data_train, data_xyz_train)
model_seasonal.fit(data_train, data_seasonal_train)

RandomForestClassifier(random_state=42)

In [133]:
# Predict probabilities
data_xyz_pred_proba = model_xyz.predict_proba(data_test)[:, 1]
data_seasonal_pred_proba = model_seasonal.predict_proba(data_test)[:, 1]

In [134]:
# Evaluation of the model using ROC AUC score

roc_auc_xyz = roc_auc_score(data_xyz_test, data_xyz_pred_proba)
roc_auc_seasonal = roc_auc_score(data_seasonal_test, data_seasonal_pred_proba)
mean_roc_auc = (roc_auc_xyz + roc_auc_seasonal) / 2

print(f"ROC AUC for xyz_vaccine: {roc_auc_xyz}")
print(f"ROC AUC for seasonal_vaccine: {roc_auc_seasonal}")
print(f"Mean ROC AUC: {mean_roc_auc}")

ROC AUC for xyz_vaccine: 0.8318755305112238
ROC AUC for seasonal_vaccine: 0.8519783325648995
Mean ROC AUC: 0.8419269315380616

In [135]:
# predicted probabilities on the full dataset

data_full_scaled = scaler.transform(data_imputed)

data_xyz_pred_full_proba = model_xyz.predict_proba(data_full_scaled)[:, 1]
data_seasonal_pred_full_proba = model_seasonal.predict_proba(data_full_scaled)[:, 1]


# preparing  the submission file in the given format
submission = pd.DataFrame({
    'respondent_id': data['respondent_id'],
    'xyz_vaccine': data_xyz_pred_full_proba,
    'seasonal_vaccine': data_seasonal_pred_full_proba
})

submission.to_csv('submission.csv', index=False)